<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 style="text-align:center">PRIVACY POLICY AND</h4>
            <h4 style="text-align:center">TERMS AND CONDITIONS OF USE</h4>
            </div>
            <div class="modal-body">
             <p style="font-size:xx-small;text-align:justify">This Privacy Policy and Terms and Conditions of Use (the "Privacy Policy" or the "Agreement") contain of the terms and conditions between Popcliqs, LLC ("Popcliqs") and you (a "User") governing the use of the service offered at the Popcliqs Website (the "Site") and through any Popcliqs mobile application (each, an "Application") (the Site and Applications are sometimes collectively referred to herein as the "Site"). The Privacy Policy also explains the use of information collected through our website and applications.</p>
<h6>PopCiqs is strongly committed to protecting your privacy and creating a strong and welcoming bond with our members</h6>
<p style="font-size:xx-small;text-align:justify">Please read this Agreement before using the Site. Use of the Site constitutes an agreement with this Privacy Policy and these Terms and Conditions (this "Agreement"), whether you register as a member of Popcliqs (“Member”) or whether you simply browse the Popcliqs site as an anonymous visitor. If you wish to become a Member and make use of the Popcliqs service (the "Service"), then please read this Agreement. By using this Site, all Users do hereby represent, warrant, understand, agree to and accept all terms and conditions contained herein. If you object to anything in this Agreement or the Popcliqs Privacy Policy, do not use the Site or the Service. The Terms and Conditions are subject to change by Popcliqs at any time, effective upon posting on the Popcliqs Website, and your use of the Site or the Service after such posting will constitute acceptance by you of such changes.</p>
<h6>ACCEPTANCE OF TERMS AND CONDITIONS AGREEMENT.</h6>
<p style="font-size:xx-small;text-align:justify">
This Agreement is an electronic contract that sets out the legally binding terms of your use of the Site and the Service. This Agreement may be modified by Popcliqs from time to time, such modifications to be effective upon posting by Popcliqs on the Site. This Agreement includes the Popcliqs Privacy Policy. By accessing the Site or becoming a Member, you accept this Agreement and agree to the terms, conditions and notices contained or referenced herein. In addition, by accessing the Site or becoming a Member, you consent to have this Agreement provided to you in electronic form.
</p>
<h6>PRIVACY POLICY.</h6>
<p style="font-size:xx-small;text-align:justify">The term "Personal Information" as used in this privacy policy means any information that may be used to identify an individual, including, but not limited to, email address, phone number or other contact information, at any location where you access Popcliqs. Popcliqs advises that in connection with registration, you do not need to use your full or true name for your member name. We urge everyone to take an active role in helping us protect their privacy by becoming aware of the policies you will encounter here.</p>
<ul style="font-size:xx-small;text-align:justify">
	<li>	We collect interaction event information and usage statistics to sustain high-quality member experiences and provide excellent member service. </li>
	<li>	Some information we request from you when you join the site. Other data are gathered indirectly from website traffic, your computer hardware and Internet connection, and usage of Popcliqs websites, applications, and services. 
	</li>
	<li>Except under certain limited circumstances set forth here and in the Popcliqs Terms & Conditions posted in Popcliqs.com, Popcliqs does not disclose your Personal Information to any third parties without your permission. Popcliqs may disclose your Personal Information if required to do so or in the good faith belief that such action is necessary to: (a) conform to the edicts of the law or comply with legal process served on Popcliqs, the Popcliqs website or any Popcliqs member; (b) protect and defend the rights or property of Popcliqs, or (c) act in urgent circumstances to protect the personal safety of members of the Popcliqs website. In addition, if Popcliqs should ever merge with or be acquired by another company, or file for bankruptcy, Popcliqs may sell the information you provide to us on this site to a third party or share your Personal Information with any company with whom we merge. </li>
	<li>You will have the ability to update the personal data you provided to us during registration from the Popcliqs website or by contacting us at the Support Center after you sign into the Popcliqs web site. </li>
	<li>Popcliqs will update this privacy policy in a timely fashion when any changes occur. </li>
</ul>
<p style="font-size:xx-small;text-align:justify">The Privacy Policy applies to both the Site and all Applications of Popcliqs. Please note that this policy applies only to Popcliqs, and not to other companies' or organizations' Websites to which we link. </p>
<h6>The Information We Collect and How We Collect It</h6>
<p style="font-size:xx-small;text-align:justify" >There are different levels of information we collect, depending upon your relationship to Popcliqs. </p>
<ul style="font-size:xx-small;text-align:justify">
	<li>	Anonymous Website Visitor (a "Visitor"): If you visit our websites, we automatically record information related to your IP address, cookie information, and aggregate information on what content you access or visit. This information is collected in the background while you move around our website.</li>
	<li>	Registered Popcliqs Member: If you choose to register as a Popcliqs member on our website, we will track and monitor site usage and aggregate usage of website features such as member activity, event creation and participation. This is in addition to the personal data collected during the registration process. </li>
	<li>	Popcliqs Mobile App: If you install or use the Popcliqs app, we may collect data to monitor system and simulation performance, and to verify your unique identity. This includes specific and general information about your computer hardware and Internet connection, which are stored but are not personally identifiable</li>
	<li>	Additionally, there are special situations to mention:<ul style="font-size:xx-small;text-align:justify">
		<li>Beta Tester: If you volunteer to serve as a beta tester for pre-release software or content, Popcliqs tracks bug reports and may monitor individual system performance in an effort to rigorously test pre-deployed technology. </li>
		<li>o	Former Member: If you cease being a member for any reason, Popcliqs may keep a copy of your registration and past activity in our database. </li>
		<li>o	Individuals Outside of the United States: Anyone using Popcliqs websites, applications, or services from outside of the United States should be aware that Personal Information collected on the websites, applications, and services may be stored and processed in the United States and by using these websites, applications, and services, you consent to any such transfer of information outside of your home country. </li>
	</ul> </li>
</ul>
   <h6>Disclosing Personal Information in Profiles, Forums, or in the Virtual World of Popcliqs.</h6>
   <p style="font-size:xx-small;text-align:justify">You may choose to disclose Personal Information in our online event creations, your Popcliqs profile, directly to other members in event meetings, or in other manners while using the Popcliqs service. Please be aware that such information is public information, may be misused by anyone accessing Popcliqs, and you should not expect privacy, safety, or confidentiality in these settings. </p>
   <p style="font-size:xx-small;text-align:justify;text-decoration:underline"><strong>How We Protect Your Personal Data
   </strong></p>
   <p style="font-size:xx-small;text-align:justify">Popcliqs complies with applicable laws and industry standards when transferring, receiving and storing visitor and member data. Access to your Personal Information is limited to those Popcliqs employees who require the information to provide products or services to you.</p>
   <p style="font-size:xx-small;text-align:justify;text-decoration:underline"><strong>Only Those 13 or Older May Register</strong></p>
   <p style="font-size:xx-small;text-align:justify">Popcliqs does not collect information from children under the age of 13 because only those individuals who are 13 years of age or older are permitted to register. Registration for our website service requires entry of a valid and eligible Date of Birth. 

</p>
<p style="font-size:xx-small;text-align:justify;text-decoration:underline"><strong>Your Consent</strong></p>
<p style="font-size:xx-small;text-align:justify">Periodically we may need to update our privacy policy to reflect changes in the types of information we collect, the means we use to collect information, and/or our usage of collected information. When this occurs, we will make reasonable efforts to alert you to these changes. Your use of the Popcliqs websites and/or any Popcliqs products or services noted above signifies your assent to this Popcliqs Privacy Policy. </p>
<p style="font-size:xx-small;text-align:justify;text-decoration:underline"><strong>How to Contact Us</strong></p>
<p style="font-size:xx-small;text-align:justify">Popcliqs welcomes your questions and comments relating to privacy. Please direct any communications at http://www.Popcliqs.com/overview/contactUs</p>
<h6>POPCLIQS IS A VENUE.</h6>
<p style="font-size:xx-small;text-align:justify">The Site is a communications platform designed to enable Users to connect and share information regarding meetings, events, and other social gatherings. Popcliqs does not take part in the interaction between and among Users, and does not control various aspects of the Site. You acknowledge that Popcliqs is a service provider that may allow people to interact online and meet in person on a real-time basis. Popcliqs generally does not regulate the content of communications or creation of meeting events. The terms of any relationship or interaction between and among Users are dictated solely by the Users themselves, and Popcliqs takes no part in such relationship or interaction. Popcliqs simply provides a venue where Users may connect and share information. Users do hereby represent, understand and expressly agree that Popcliqs does not have control over the accuracy, authenticity, legality, morality, ethicality or any other aspect whatsoever of the information posted or communicated by any User, and that Popcliqs does not assume responsibility for any of the actions whatsoever of Users. Popcliqs makes no representations about the accuracy, reliability, suitability, reliability, timeliness, legality or accuracy of the information provided by Users through the Site whether in public, private or offline interactions. Popcliqs does not assume and expressly disclaims any liability that may result from the use of this information and any interactions amongst Users and/or Visitors. Popcliqs is not responsible for the conduct, whether online or offline, of any User or Visitor of the Site or Member of the Service. All Users do hereby expressly agree not to hold Popcliqs (or Popcliqs’s officers, directors, investors, subsidiaries, agents, assignees, representatives, advertisers, marketing partners, licensors, independent contractors, recruiters, corporate partners, or employees, or your employer, if you become a Member through your employer, hereinafter “Affiliates”) liable for any information, instruction, advice or services delivered which originated through the Site and Popcliqs and its Affiliates expressly disclaims any liability whatsoever for any damage, suits, claims, and/or controversies that have arisen or may arise, whether known or unknown therefrom.</p>
<h6>ELIGIBILITY; REPRESENTATIONS AND WARRANTIES.</h6>
<p style="font-size:xx-small;text-align:justify;text-decoration:underline"><strong>Eligibility Criteria. </strong></p>
<ul style="font-size:xx-small;text-align:justify;">To be eligible to use our Services, you must meet the following criteria:
<li >Our Services are available only to individuals who are at least thirteen (13) years of age or older. If you are less than eighteen (18) years of age, you must have your parent or legal guardian’s permission to use the Site, as well as have them read and agree to this Agreement. If you do not meet the above age requirements, do not register to use the Site or Services.</li>
<li>The Site and the Services are currently available only to individuals who are legally in the jurisdiction of the United States. This Site is controlled and operated by Popcliqs from its offices within Georgia, United States of America. Popcliqs makes no representation that the Site, Applications, or related information offered by Popcliqs are appropriate or available in other locations. Those who choose to access the Site from other locations do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable. </li>
<li>You must not be a competitor of Popcliqs or using our Services for reasons that are in competition with Popcliqs.</li>
</ul>
<h6>Representations and Warranties.</h6>
<p style="font-size:xx-small;text-align:justify">You represent and warrant for the benefit of Popcliqs, Popcliqs’s suppliers, and any third parties mentioned on the Site, in addition to other representations and obligations contained in these Terms, that: (a) you possess the legal right and ability to enter into and make the representations and warranties contained in this Agreement; (b) all required information (as described herein) submitted by you to the Site is true and accurate; (c) you will keep your registration information current; (d) you will be responsible for all use of your password even if such use was conducted without your authority or permission; (e) you will not use the Site, Applications or Services for any purpose that is unlawful or prohibited by this Agreement; (f) you are the owner of the Materials and they are original to you; (g) the information and/or Materials do not infringe any third party right, such as copyright, trademark, and publicity/privacy right; (h) the information and/or Materials do not constitute defamation or libel or otherwise violate the law, and (i) you agree to defend, indemnify, and hold Popcliqs (and its employees, representative, agents, and assigns) harmless from breaches of (a) through (h). </p>
<p style="font-size:xx-small;text-align:justify">You hereby authorize Popcliqs to verify your representations and warranties herein, and you acknowledge that Popcliqs reserves the right, but not the obligation, to verify such representations and warranties, and to take action it deems appropriate in its sole discretion, including but not limited to terminating your membership or use of the Site, should it determine, in its sole opinion, that you have violated any representation or warranty or any other provision of this Agreement.</p>
<p style="font-size:xx-small;text-align:justify">NOTWITHSTANDING THE FOREGOING, POPCLIQS DISCLAIMS ANY LIABILITY WHATSOEVER FOR ANY MISSTATEMENTS AND/OR MISREPRESENTATIONS MADE BY ANY USERS OF THE SITE. USERS DO HEREBY REPRESENT, UNDERSTAND AND AGREE TO HOLD POPCLIQS HARMLESS FOR ANY MISSTATEMENTS AND/OR MISREPRESENTATIONS MADE BY ANY USERS OF THIS SITE.</p>
<h6>LIMITED NON-COMMERCIAL LICENSE TO USE SITE</h6>
<p style="font-size:xx-small;text-align:justify">Popcliqs hereby grants you the limited right to view and use the Site only for the purposes of viewing events, creating events and participating in events. Popcliqs reserves the right to suspend, ban, reset any and all features of your account in its sole discretion, your access to all or any portions of the Site. Unless you have received specific written permission from Popcliqs, you may not (a) "frame" or otherwise impose editorial comment, commercial material or any information or content on, or in proximity to, content displayed on the Site, or (b) alter or modify any content on the Site. Without limiting other restrictions, you agree not to reproduce, transmit, sell, or otherwise exploit the Site and/or Applications for any commercial purpose. </p>
<p style="font-size:xx-small;text-align:justify;">The Site will allow members to create events subject to the following conditions:</p>
<ul style="font-size:xx-small;text-align:justify;">
<li>You understand that information that is transmitted to or via the Site is the sole responsibility of the person from whom the information originated. This means you, and not Popcliqs, are entirely responsible for the events that you create and in which you participate. Further, you understand that by using the Site you may be exposed to materials that are offensive, objectionable or indecent. </li>
<li>You shall not create a member name or nickname, publish through the Site any information or materials which are indecent, libelous, defamatory, obscene, threatening, invasive of privacy or publicity rights, abusive, illegal, harassing, contain expressions of hatred, bigotry, racism or pornography, depicts graphic or gratuitous violence, or are otherwise objectionable, or that would constitute or encourage a criminal offense, violate the rights of any party or violate any law. </li>
<li>	Your information, materials, member name and/or nickname will not disparage in any manner Popcliqs, its Licensors, or their Applications, products, or services and sites. </li>
<li>Your Materials, member name and/or nickname shall not infringe the copyright, trademark, publicity/privacy right or other intellectual property right of any third party. </li>
<li>	You shall not upload to, distribute through or otherwise publish through the Site any information or materials that contain viruses or any other computer code, corrupt files or programs designed to interrupt, destroy or limit the functionality or disrupt any software, hardware, telecommunications, networks, servers or other equipment.</li></ul>
<h6>LIMITED NON-COMMERCIAL LICENSE TO USE APPLICATIONS</h6>
<p style="font-size:xx-small;text-align:justify;">Without limiting your obligations and restrictions, your limited license to the Site is subject to the following conditions:</p><ul style="font-size:xx-small;text-align:justify;"><li>	The Site and applications that are made available to you are the copyrighted work of Popcliqs and/or its suppliers. Certain applications may be owned by third parties and distributed under third party agreements and you agree that Popcliqs shall not be responsible for any loss or damage of any sort relating to your dealings with such third parties. </li>
<li>You shall provide and properly maintain at your expense a computing system and Internet connection that meets or exceeds Popcliqs’s system requirements for access and use of the Site and application. Popcliqs does not provide Internet access, and you are responsible for all expenses and fees associated with your computing system and Internet connection. </li>
<li>	Popcliqs may cease support of any application at any time in its sole discretion.

</li> </ul>
<h6>EXCLUSIVE USE; OBLIGATION FOR USING YOUR PASSWORD</h6>
<p style="font-size:xx-small;text-align:justify;">Your account is for your sole, personal use, you may not authorize others to use your account, and you may not assign or otherwise transfer your account to any other person or entity.

ALL CONTENT OR INSTRUCTIONS TRANSMITTED BY OR RECEIVED FROM ANYONE PRESENTING YOUR PASSWORD ON THE SITE WILL BE DEEMED BINDING ON YOU. You agree that you are solely liable for all actions taken via your password, whether or not made with your knowledge or authority. You agree to guard your password carefully, with the full awareness that a failure to keep it secure will enable others to engage in transactions through the Site for which you will be legally responsible. If you suspect that someone may have obtained access to your password who is not intended to have authority to act on your behalf, please contact Popcliqs immediately to authorize Popcliqs to deny access to the Site to anyone else presenting your password. 
</p>
<h6>INFORMATION PROVIDED BY USERS.</h6>
<p style="font-size:xx-small;text-align:justify;">You are responsible for providing accurate, current and complete information in connection with your registration for use of the Site. Popcliqs is not responsible for any claims relating to any inaccurate, untimely or incomplete information provided by users of the Site.</p>
<p style="font-size:xx-small;text-align:justify;">You are solely responsible for any content, messages, photos, videos, reviews or profiles (collectively, “Content”) that you publish or display (hereinafter, "post") on the Site, or transmit to other users of the Site. You will not post on the Site, or transmit to other users, any defamatory, inaccurate, abusive, obscene, profane, offensive, sexually oriented, threatening, harassing, racially offensive, or illegal material, or any material that infringes or violates another party’s rights (including, but not limited to, intellectual property rights, and rights of privacy and publicity). You will not provide inaccurate, misleading or false information to Popcliqs or to any other user of the Site.</p>
<p style="font-size:xx-small;text-align:justify;">You understand and agree that Popcliqs may (but has no obligation to) review and delete any Content, in each case in whole or in part, that in the sole judgment of Popcliqs violates this Agreement or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of users of the Site.</p>
<p style="font-size:xx-small;text-align:justify;">
By posting Content to any public or member area of the Site you automatically grant, and you represent and warrant that you have the right to grant, to Popcliqs, its Affiliates, licensees and successors, an irrevocable, perpetual, non-exclusive, fully paid, worldwide license to use, copy, perform, display, reproduce, adapt, modify and distribute such information and content and to prepare derivative works of, or incorporate into other works, such information and content, and to grant and authorize sublicenses of the foregoing. You further represent and warrant that public posting and use of your Content by Popcliqs will not infringe or violate the rights of any third party.
</p>
<p style="font-size:xx-small;text-align:justify;">Your use of the Service, including but not limited to the Content you post on the Service, must be in accordance with any and all applicable laws and regulations.</p>
<p style="font-size:xx-small;text-align:justify;">Opinions, advice, statements, offers, or other information or content made available on the Site or through the Service, but not directly by Popcliqs, are those of their respective authors. Such authors are solely responsible for such content. Popcliqs does not: (i) guarantee the accuracy, completeness, or usefulness of any information on the Site or available through the Service, or (ii) adopt, endorse or accept responsibility for the accuracy or reliability of any opinion, advice, or statement made by any party that appears on the Site or through the Service. Under no circumstances will Popcliqs or its Affiliates be responsible for any loss or damage resulting from: a) your reliance on information or other content posted on the Site or transmitted to or by any user of the Site or Service; or b) reviews or comments made about you on the Site by other users.</p>
<h6>RELEASE.</h6>
<p style="font-size:xx-small;text-align:justify;">In the event you and another User or Visitor exchange information, establish a relationship, or agree to meet online or in person, such agreement is solely between you and such other User; Popcliqs is not a party to any such agreement. Any issues concerning the same must be resolved directly by you and such third party. Popcliqs will not be held responsible and expressly disclaims any liability whatsoever for any claims, demands or damages direct or indirect of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such issues. By using this Site, you do hereby represent, understand, and expressly agree to hold Popcliqs harmless for any claim or controversy that may arise from any disputes between you and any other user(s) of the Site. YOU ACKNOWLEDGE AND AGREE THAT POPCLIQS IS UNDER NO DUTY TO, AND SHALL NOT, MONITOR USERS AND/OR USERS’ PROFILES, ACTIONS, COMMENTS, AND GENERAL USAGE OF THE SITE. ACCORDINGLY, YOU KNOWINGLY AND VOLUNTARILY RELEASE POPCLIQS FROM ANY LIABILITY FOR NOT SUSPENDING THE PRIVILEGES TO ANY USER FOR NOT ADHERING TO THE POLICIES OF THE SITE. You agree to take reasonable precautions in all interactions with other users of the Site, particularly if you decide to meet offline or in person. By using this Site, you do hereby agree to report any alleged improprieties of any users therein to Popcliqs immediately by notifying Popcliqs of the same via electronic correspondence.</p>
<h6>TERM AND TERMINATION.</h6>
<p style="font-size:xx-small;text-align:justify;">The term of this Agreement shall commence on the Effective Date and shall continue for so long as you use the Site, unless Popcliqs terminates your usage as provided below. </p>
<p style="font-size:xx-small;text-align:justify;">Popcliqs reserves the right, in its sole discretion, to terminate your access to all or part of the Popcliqs Site, to remove your profile and/or any content posted by or about you, from the Site, and/or to terminate your membership in Popcliqs, for any reason or no reason, with or without notice. Following any termination of any member’s use of the Site, Popcliqs reserves the right to send a notice thereof to other members which whom you have corresponded.</p>
<h6>LINKS TO EXTERNAL SITES.</h6>
<p style="font-size:xx-small;text-align:justify;">Links from the Site to external sites (including external sites that are framed by Popcliqs) or inclusion of advertisements do not constitute an endorsement by Popcliqs of such sites or the content, products, advertising and other materials presented on such sites or of the products and services that are the subject of such advertisements, but are for users’ reference and convenience. Users access them at their own risk. It is the responsibility of the user to evaluate the content and usefulness of the information obtained from other sites. Popcliqs does not control such sites, and is not responsible for their content. Users further acknowledge that use of any site controlled, owned or operated by third parties is governed by the terms and conditions of use for those sites, and not by Popcliqs’s Terms and Conditions and Privacy Policy. Popcliqs expressly disclaims any liability derived from the use and/or viewing of links that may appear on this Site. All users hereby agree to hold Popcliqs harmless from any liability that may result from the use of links that may appear on the Site.

</p>
<h6>COPPA COMPLIANCE.</h6>
<p style="font-size:xx-small;text-align:justify;">Users agree to monitor children’s use of the Internet. Popcliqs will not knowingly collect any information from children under thirteen (13) years of age. You must identify your age during the registration process. Popcliqs takes the Children’s Online Privacy Protection Act of 1998 (COPPA) as well as all FTC regulations very seriously. That being said, we do not assume any responsibility for any misrepresentations regarding your age or parental consent when using this Site. Should we determine that you provided any false information to us when using this Site, your membership will be terminated immediately.

</p>
<h6>DISCLAIMER OF WARRANTY.</h6>
<p style="font-size:xx-small;text-align:justify;">EXCEPT IF EXPRESSLY PROVIDED OTHERWISE IN A WRITTEN AGREEMENT  BETWEEN YOU AND POPCLIQS, THE SITE AND APPLICATIONS OFFERED AT OR THROUGH THE SITE, AND APPLICATIONS ARE PROVIDED TO YOU "AS IS" WITHOUT WARRANTY OF ANY KIND AND WITH ALL RISKS. POPCLIQS HEREBY DISCLAIMS TO THE MAXIMUM EXTENT PERMITTED BY LAW (A) ALL WARRANTIES EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE; AVAILABILITY OF THE SITE AND APPLICATIONS; LACK OF VIRUSES, WORMS, TROJAN HORSES, OR OTHER CODE THAT MANIFESTS CONTAMINATING OR DESTRUCTIVE PROPERTIES; ACCURACY, COMPLETENESS, RELIABILITY, TIMELINESS, CURRENCY, OR USEFULNESS OF ANY INFORMATION ON THE SITE; AND (B) ANY DUTIES OF REASONABLE CARE, WORKMANLIKE EFFORT OR LACK OF NEGLIGENCE IN CONNECTION WITH THE SITE, APPLICATIONS, OR RELATED INFORMATION. THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT IN CONNECTION WITH THE SITE, APPLICATIONS, AND RELATED INFORMATION IS BORNE BY YOU. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF IMPLIED WARRANTIES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU. 

</p>
<p style="font-size:xx-small;text-align:justify;">IN ADDITION, POPCLIQS DISCLAIMS ANY WARRANTIES OF NON-INFRINGEMENT, TITLE OR QUIET ENJOYMENT IN CONNECTION WITH THE SITE, APPLICATIONS, AND RELATED INFORMATION. </p>
<h6>Third Party Content. </h6>
<p style="font-size:xx-small;text-align:justify;">Opinions, advice, statements, offers, or other information or content made available through the Services, but not directly by Popcliqs, are those of their respective authors, and should not necessarily be relied upon. Such authors are solely responsible for such content. POPCLIQS DOES NOT: (i) GUARANTEE THE ACCURACY, COMPLETENESS OR USEFULNESS OF ANY INFORMATION PROVIDED ON THE SITE, OR (ii) ADOPT, ENDORSE OR ACCEPT RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE, OR STATEMENT MADE BY ANY PARTY OTHER THAN POPCLIQS. UNDER NO CIRCUMSTANCES WILL POPCLIQS BE RESPONSIBLE FOR ANY LOSS OR DAMAGE RESULTING FROM ANYONE’S RELIANCE ON INFORMATION OR OTHER CONTENT POSTED ON THE SERVICES, OR TRANSMITTED TO OR BY ANY USERS.</p>
<h6>ASSUMPTION OF RISK.</h6>
<p style="font-size:xx-small;text-align:justify;">You assume all risk when using the Services, including but not limited to all of the risks associated with any online or offline interactions with Members of the site. You agree to take all necessary precautions, including but not limited to following the recommendations set forth herein, when interacting with others Members of the site.</p>
<h6>LIMITATION OF LIABILITY.</h6>
<p style="font-size:xx-small;text-align:justify;text-decoration:underline;"><strong>Incidental Damages and Aggregate Liability. </strong></p>
<p style="font-size:xx-small;text-align:justify;">In no event will Popcliqs be liable for any indirect, special, incidental, or consequential damages, losses or expenses arising out of or relating to the use or inability to use the Site, including without limitation damages related to any information received from the Site, removal of content from the Site, including profile information, any email distributed to any user or any linked web site or use thereof or inability to use by any party, or in connection with any termination of your subscription or ability to access the Site, failure of performance, error, omission, interruption, defect, delay in operation or transmission, computer virus or line or system failure, even if Popcliqs, or representatives thereof, are advised of the possibility of such damages, losses or expenses. UNDER NO CIRCUMSTANCES WILL POPCLIQS’S AGGREGATE LIABILITY, IN ANY FORM OF ACTION WHATSOEVER IN CONNECTION WITH THIS AGREEMENT OR THE USE OF THE SERVICES OR THE SITE, EXCEED THE PRICE PAID BY YOU FOR YOUR ACCOUNT, OR, IF YOU HAVE NOT PAID POPCLIQS FOR THE USE OF ANY SERVICES, THE AMOUNT OF US $25.00 OR ITS EQUIVALENT. YOU AGREE THAT THE DAMAGE EXCLUSIONS IN THIS AGREEMENT SHALL APPLY EVEN IF ANY REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
<p style="font-size:xx-small;text-align:justify;text-decoration:underline;"><strong>No Liability for non-Popcliqs Actions. 

</strong></p>
<p style="font-size:xx-small;text-align:justify;">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL POPCLIQS BE LIABLE FOR ANY DAMAGES WHATSOEVER, WHETHER DIRECT, INDIRECT, GENERAL, SPECIAL, COMPENSATORY, CONSEQUENTIAL, AND/OR INCIDENTAL, ARISING OUT OF OR RELATING TO THE CONDUCT OF YOU OR ANYONE ELSE IN CONNECTION WITH THE USE OF THE SITE, INCLUDING WITHOUT LIMITATION, BODILY INJURY, EMOTIONAL DISTRESS, AND/OR ANY OTHER DAMAGES RESULTING FROM INTERACTIONS WITH OTHER MEMBERS OF THE SITE, WHETHER ONLINE OR OFFLINE. THIS INCLUDES ANY CLAIMS, LOSSES OR DAMAGES ARISING FROM THE CONDUCT OF USERS WHO HAVE REGISTERED UNDER FALSE PRETENSES OR WHO ATTEMPT TO DEFRAUD OR HARM YOU.</p>
<p style="font-size:xx-small;text-align:justify;">In addition to the preceding paragraphs of this section and other provisions of this Agreement, any advice that may be posted on the Site is for informational purposes only and is not intended to replace or substitute for any professional financial, medical, legal, or other advice. Popcliqs makes no representations or warranties and expressly disclaims any and all liability concerning any treatment, action by, or effect on any person following the information offered or provided within or through the Site. If you have specific concerns or a situation arises in which you require professional or medical advice, you should consult with an appropriately trained and qualified specialist.</p>
<h6>INDEMNIFICATION.</h6>
<p style="font-size:xx-small;text-align:justify;">By agreeing to the terms of this Agreement, Users of the Site agree to indemnify, defend and hold harmless Popcliqs and its Affiliates from and against any and all claims, losses, expenses or demands of liability, including attorneys’ fees and costs incurred by Popcliqs and its Affiliates in connection with any claim by a third party (including an intellectual property claim) arising out of (i) materials and content you submit, post or transmit through the Site; (ii) use of the Site and/or Service by you in violation of this Agreement or in violation of any applicable law; (iii) any services provided by a User; and (iv) any interaction between or among you and any of the following: another User, a Visitor, or any third party. Users further agree that they will cooperate as reasonably required in the defense of such claims. Popcliqs and its Affiliates reserve the right, at their own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by users, and users shall not, in any event, settle any claim or matter without the written consent of Popcliqs. Users further agree to hold harmless Popcliqs and its Affiliates from any claim arising from a third party’s use of information or materials of any kind that users post to the Site.

</p>
<h6>NOTICE AND TAKE DOWN PROCEDURES; COPYRIGHT AGENT.</h6>
<p style="font-size:xx-small;text-align:justify;">If you believe any materials accessible on or from Site infringe your copyright, you may request removal of those materials (or access thereto) from this Site by contacting Popcliqs’s copyright agent (identified below) and providing the following information:</p>
<ul style="font-size:xx-small;text-align:justify;">
	<li>Identification of the copyrighted work that you believe to be infringed. Please describe the work, and where possible include a copy or the location (e.g., URL) of an authorized version of the work.</li>
	<li>Identification of the material that you believe to be infringing and its location. Please describe the material, and provide us with its URL or any other pertinent information that will allow us to locate the material.</li>
	<li>Your name, address, telephone number and (if available) e-mail address.</li>
	<li>A statement that you have a good faith belief that the complained of use of the materials is not authorized by the copyright owner, its agent, or the law.</li>
	<li>A statement that the information that you have supplied is accurate, and indicating that "under penalty of perjury," you are the copyright owner or are authorized to act on the copyright owner’s behalf.</li>
	<li>A signature or the electronic equivalent from the copyright holder or authorized representative.</li>
</ul>
<p style="font-size:xx-small;text-align:justify;">Popcliqs’s agent for copyright issues relating to this Site is as follows:</p>
<p style="font-size:xx-small;text-align:justify;">Copyright Agent
http://www.Popcliqs.com/overview/contactUs

In an effort to protect the rights of copyright owners, Popcliqs maintains a policy for the termination, in appropriate circumstances, of Members and other users of this Site who are repeat infringers.
</p>
<h6>NOTICE OF TRADEMARK RIGHTS.</h6>
<p style="font-size:xx-small;text-align:justify;">EXCEPT AS EXPRESSLY PROVIDED HEREIN BY THIS AGREEMENT, NEITHER POPCLIQS, NOR ANY THIRD PARTY HAS CONFERRED UPON YOU BY IMPLICATION, ESTOPPEL OR OTHERWISE, ANY LICENSE OR RIGHT UNDER ANY PATENT, TRADEMARK, COPYRIGHT OR OTHER PROPRIETARY RIGHTS TO USE THE SITE OR ANY APPLICATIONS OFFERED ON THE SITE. NO OWNERSHIP RIGHTS ARE OR WILL BE ASSIGNED TO YOU. The service marks and trademarks Popcliqs and the Popcliqs logo are service marks owned by Popcliqs. Any other trademarks, service marks, logos and/or trade names appearing on the Site are the property of their respective owners. Users acknowledge the rights of Popcliqs and the respective third parties in those marks. Users may not copy or use any of these marks, logos or trade names without the prior written permission of the owner as expressly allowed by this Agreement.</p>
<h6>JURISDICTION AND CHOICE OF LAW.</h6>
<p style="font-size:xx-small;text-align:justify;">If there is any dispute arising out of the Site and/or the Service, by using the Site, you expressly agree that any such dispute shall be governed by the laws of the State of Georgia, without regard to its conflict of law provisions, and you expressly agree and consent to the exclusive jurisdiction and venue of the state and federal courts of the State of Georgia, Cobb County, for the resolution of any such dispute.</p>
<h6>INVALID PROVISIONS; SEVERABILITY.  </h6>
<p style="font-size:xx-small;text-align:justify;">Any provision of this Agreement which is prohibited and unenforceable in any jurisdiction shall, as to such jurisdiction, be ineffective to the extent of such prohibitive or enforceability without invalidating the remaining provisions hereof or affecting the validity or enforceability of such provisions in any other jurisdiction. Should any provisions of this Agreement be unenforceable, the remaining provisions of this Agreement shall remain in full force and effect.</p>
<h6>MISCELLANEOUS.</h6>
<p style="font-size:xx-small;text-align:justify;">Nothing in this Agreement shall be construed as making either party the partner, joint venturer, agent, legal representative, employer, contractor or employee of the other. Nor is any Service Seeker or Service Provider a partner, joint venturer, agent, legal representative, employer, contractor or employee of Popcliqs. Neither party shall have, or hold itself out to any third party as having, any authority to make any statements, representations or commitments of any kind, or to take any action, that shall be binding on the other, except as provided for herein or authorized in writing by the party to be bound. This Agreement will be binding on and will inure to the benefit of the legal representatives, successors and assigns of the parties hereto.

</p>
<h6>CONTACT INFORMATION.</h6>
<p style="font-size:xx-small;text-align:justify;">If you have any questions or need further information as to the Site or Service provided by Popcliqs, or need to notify Popcliqs as to any matters relating to the Site or Service please contact Popcliqs at:</p>
<p style="font-size:xx-small;text-align:justify;">Legal Department</p>
<p style="font-size:xx-small;text-align:justify;">http://www.Popcliqs.com/overview/contactUs </p>    

            </div>

                <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-dismiss="modal">
                close</button>
                </div>
        </div>
    </div>
</div>
